### ISSUE TITLE
4.2.0 Crashing on Samsung DeX upon connect

### ISSUE THREAD

**Issue by Cerlancism** [iiordanov/remote-desktop-clients#209]
Works fine before 4.1.0, but having bad color issue like this one: https://github.com/iiordanov/remote-desktop-clients/issues/190. Now it crashes whenever pressing connect on DeX, work fines without DeX though.

<details>
<summary>logcat</summary> 
<pre>
05-12 15:19:44.965 23962 23962 D ViewRootImpl: updatePointerIcon pointerType = 10121, calling pid = 23962
05-12 15:19:44.965 23962 23962 D InputManager: setPointerIconType iconId = 10121, callingPid = 23962
05-12 15:19:45.090 23962 23962 D ViewRootImpl: updatePointerIcon pointerType = 10121, calling pid = 23962
05-12 15:19:45.091 23962 23962 D InputManager: setPointerIconType iconId = 10121, callingPid = 23962
05-12 15:19:45.355 23962 23962 D ViewRootImpl: updatePointerIcon pointerType = 1002, calling pid = 23962
05-12 15:19:45.355 23962 23962 D InputManager: setPointerIconType iconId = 1002, callingPid = 23962
05-12 15:19:45.444 23962 23962 D ViewRootImpl@df28fdc[bVNC: Intuitive, secure VNC client]: ViewPostIme pointer 0
05-12 15:19:45.445 23962 23962 D ViewRootImpl: updatePointerIcon pointerType = 1002, calling pid = 23962
05-12 15:19:45.445 23962 23962 D InputManager: setPointerIconType iconId = 1002, callingPid = 23962
05-12 15:19:45.535 23962 23962 D ViewRootImpl@df28fdc[bVNC: Intuitive, secure VNC client]: ViewPostIme pointer 1
05-12 15:19:45.535 23962 23962 D ViewRootImpl: updatePointerIcon pointerType = 1002, calling pid = 23962
05-12 15:19:45.536 23962 23962 D InputManager: setPointerIconType iconId = 1002, callingPid = 23962
05-12 15:19:45.549 23962 23981 D OpenGLRenderer: makeCurrent EglSurface : 0x73727ccc00 -> 0x0
05-12 15:19:45.549 23962 23981 D OpenGLRenderer: destroyEglSurface : 0x73727ccc00
05-12 15:19:45.549 23962 23981 I mali_egl: eglDestroySurface() in
05-12 15:19:45.550 23962 23981 I mali_winsys: delete_surface() [1920x1018] return
05-12 15:19:45.551 23962 23981 I mali_egl: eglDestroySurface() out
05-12 15:19:45.551 23962 23981 W libEGL  : EGLNativeWindowType 0x737a8f9750 disconnect failed
05-12 15:19:45.551 23962 23981 D OpenGLRenderer: ~ReliableSurface : 0x737a8f9740
05-12 15:19:45.551 23962 23981 D OpenGLRenderer: endAllActiveAnimators on 0x72ea45eb00 (RippleDrawable) with handle 0x737a6e8020
05-12 15:19:45.551 23962 23962 D ViewRootImpl@df28fdc[bVNC: Intuitive, secure VNC client]: dispatchDetachedFromWindow
05-12 15:19:45.558 23962 23962 D InputTransport: Input channel destroyed: '16eb156', fd=67
05-12 15:19:45.558 23962 23962 W InputEventReceiver: Attempted to finish an input event but the input event receiver has already been disposed.
05-12 15:19:45.560 23962 23962 D ViewRootImpl@7753dda[bVNC]: MSG_WINDOW_FOCUS_CHANGED 1 1
05-12 15:19:45.560 23962 23962 D InputMethodManager: prepareNavigationBarInfo() DecorView@97a79ca[bVNC]
05-12 15:19:45.560 23962 23962 D InputMethodManager: getNavigationBarColor() -855310
05-12 15:19:45.564 23962 23962 D InputMethodManager: prepareNavigationBarInfo() DecorView@97a79ca[bVNC]
05-12 15:19:45.564 23962 23962 D InputMethodManager: getNavigationBarColor() -855310
05-12 15:19:45.564 23962 23962 V InputMethodManager: Starting input: tba=com.iiordanov.freebVNC ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
05-12 15:19:45.564 23962 23962 D InputMethodManager: startInputInner - Id : 2
05-12 15:19:45.564 23962 23962 I InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
05-12 15:19:45.566 23962 23962 D InputTransport: Input channel destroyed: 'ClientS', fd=72
05-12 15:19:45.566 23962 23962 D ViewRootImpl: updatePointerIcon pointerType = 10121, calling pid = 23962
05-12 15:19:45.567 23962 23962 D InputManager: setPointerIconType iconId = 10121, callingPid = 23962
05-12 15:19:45.574 23962 23981 D OpenGLRenderer: makeCurrent EglSurface : 0x0 -> 0x74092af380
05-12 15:19:45.575 23962 23962 E ViewRootImpl: sendUserActionEvent() mView returned.
05-12 15:19:45.823 23962 23962 D ViewRootImpl: updatePointerIcon pointerType = 1002, calling pid = 23962
05-12 15:19:45.824 23962 23962 D InputManager: setPointerIconType iconId = 1002, callingPid = 23962
05-12 15:19:45.839 23962 23962 D ViewRootImpl: updatePointerIcon pointerType = 1008, calling pid = 23962
05-12 15:19:45.839 23962 23962 D InputManager: setPointerIconType iconId = 1008, callingPid = 23962
05-12 15:19:45.873 23962 23962 D ViewRootImpl: updatePointerIcon pointerType = 10121, calling pid = 23962
05-12 15:19:45.873 23962 23962 D InputManager: setPointerIconType iconId = 10121, callingPid = 23962
05-12 15:19:45.906 23962 23962 D ViewRootImpl: updatePointerIcon pointerType = 1008, calling pid = 23962
05-12 15:19:45.906 23962 23962 D InputManager: setPointerIconType iconId = 1008, callingPid = 23962
05-12 15:19:46.058 23962 23962 D ViewRootImpl: updatePointerIcon pointerType = 1002, calling pid = 23962
05-12 15:19:46.059 23962 23962 D InputManager: setPointerIconType iconId = 1002, callingPid = 23962
05-12 15:19:46.107 23962 23962 D ViewRootImpl: updatePointerIcon pointerType = 10121, calling pid = 23962
05-12 15:19:46.107 23962 23962 D InputManager: setPointerIconType iconId = 10121, callingPid = 23962
05-12 15:19:46.157 23962 23962 D ViewRootImpl: updatePointerIcon pointerType = 1002, calling pid = 23962
05-12 15:19:46.158 23962 23962 D InputManager: setPointerIconType iconId = 1002, callingPid = 23962
05-12 15:19:46.343 23962 23962 D ViewRootImpl: updatePointerIcon pointerType = 10121, calling pid = 23962
05-12 15:19:46.343 23962 23962 D InputManager: setPointerIconType iconId = 10121, callingPid = 23962
05-12 15:19:46.410 23962 23962 D ViewRootImpl: updatePointerIcon pointerType = 1002, calling pid = 23962
05-12 15:19:46.410 23962 23962 D InputManager: setPointerIconType iconId = 1002, callingPid = 23962
05-12 15:19:46.511 23962 23962 D ViewRootImpl@7753dda[bVNC]: ViewPostIme pointer 0
05-12 15:19:46.511 23962 23962 D ViewRootImpl: updatePointerIcon pointerType = 1002, calling pid = 23962
05-12 15:19:46.512 23962 23962 D InputManager: setPointerIconType iconId = 1002, callingPid = 23962
05-12 15:19:46.630 23962 23962 D ViewRootImpl@7753dda[bVNC]: ViewPostIme pointer 1
05-12 15:19:46.631 23962 23962 D ViewRootImpl: updatePointerIcon pointerType = 1002, calling pid = 23962
05-12 15:19:46.631 23962 23962 D InputManager: setPointerIconType iconId = 1002, callingPid = 23962
05-12 15:19:46.643 23962 23962 D MainConfiguration: onMenuOpened
05-12 15:19:46.643 23962 23962 D MainConfiguration: onMenuOpened
05-12 15:19:46.643 23962 23962 E MainConfiguration: Default Input Mode Item: TOUCH_ZOOM_MODE
05-12 15:19:46.643 23962 23962 E MainConfiguration: Input Mode Item: TOUCHPAD_MODE
05-12 15:19:46.643 23962 23962 E MainConfiguration: Input Mode Item: TOUCH_ZOOM_MODE
05-12 15:19:46.643 23962 23962 E MainConfiguration: Input Mode Item: TOUCH_ZOOM_MODE_DRAG_PAN
05-12 15:19:46.644 23962 23962 E MainConfiguration: Input Mode Item: SINGLE_HANDED_MODE
05-12 15:19:46.668 23962 23962 D ViewRootImpl@89b0b8[PopupWindow:f79615]: setView = android.widget.PopupWindow$PopupDecorView@4c87e91 TM=true MM=false
05-12 15:19:46.671 23962 23962 V InputMethodManager: Not IME target window, ignoring
05-12 15:19:46.678 23962 23962 D ViewRootImpl@89b0b8[PopupWindow:f79615]: Relayout returned: old=(0,0,1920,1018) new=(1658,48,1916,576) req=(258,528)0 dur=7 res=0x7 s={true 495738212352} ch=true
05-12 15:19:46.680 23962 23981 D OpenGLRenderer: createReliableSurface : 0x730745c1c0(0x736c4cd000)
05-12 15:19:46.681 23962 23981 I mali_winsys: new_window_surface() [322x592] return: 0x3000
05-12 15:19:46.691 23962 23962 D AbsListView:  in onLayout changed 
05-12 15:19:46.694 23962 23981 D OpenGLRenderer: makeCurrent EglSurface : 0x74092af380 -> 0x737a83a800
05-12 15:19:46.700 23962 23981 D OpenGLRenderer: makeCurrent EglSurface : 0x737a83a800 -> 0x74092af380
05-12 15:19:46.704 23962 23962 D ViewRootImpl@89b0b8[PopupWindow:f79615]: MSG_WINDOW_FOCUS_CHANGED 1 1
05-12 15:19:46.704 23962 23962 V InputMethodManager: Not IME target window, ignoring
05-12 15:19:46.708 23962 23981 D OpenGLRenderer: makeCurrent EglSurface : 0x74092af380 -> 0x737a83a800
05-12 15:19:46.713 23962 23981 D OpenGLRenderer: makeCurrent EglSurface : 0x737a83a800 -> 0x74092af380
05-12 15:19:46.714 23962 23962 D ViewRootImpl@89b0b8[PopupWindow:f79615]: MSG_RESIZED: frame=(1658,48,1916,576) ci=(0,0,0,0) vi=(0,0,0,0) or=2
05-12 15:19:46.714 23962 23962 D ViewRootImpl@7753dda[bVNC]: MSG_WINDOW_FOCUS_CHANGED 0 1
05-12 15:19:46.714 23962 23962 D InputMethodManager: prepareNavigationBarInfo() DecorView@97a79ca[bVNC]
05-12 15:19:46.714 23962 23962 D InputMethodManager: getNavigationBarColor() -855310
05-12 15:19:46.725 23962 23981 D OpenGLRenderer: makeCurrent EglSurface : 0x74092af380 -> 0x737a83a800
05-12 15:19:46.733 23962 23981 D OpenGLRenderer: makeCurrent EglSurface : 0x737a83a800 -> 0x74092af380
05-12 15:19:46.741 23962 23981 D OpenGLRenderer: makeCurrent EglSurface : 0x74092af380 -> 0x737a83a800
05-12 15:19:46.744 23962 23981 D OpenGLRenderer: makeCurrent EglSurface : 0x737a83a800 -> 0x74092af380
05-12 15:19:46.758 23962 23981 D OpenGLRenderer: makeCurrent EglSurface : 0x74092af380 -> 0x737a83a800
05-12 15:19:46.760 23962 23981 D OpenGLRenderer: makeCurrent EglSurface : 0x737a83a800 -> 0x74092af380
05-12 15:19:46.775 23962 23981 D OpenGLRenderer: makeCurrent EglSurface : 0x74092af380 -> 0x737a83a800
05-12 15:19:46.778 23962 23981 D OpenGLRenderer: makeCurrent EglSurface : 0x737a83a800 -> 0x74092af380
05-12 15:19:46.792 23962 23981 D OpenGLRenderer: makeCurrent EglSurface : 0x74092af380 -> 0x737a83a800
05-12 15:19:46.795 23962 23981 D OpenGLRenderer: makeCurrent EglSurface : 0x737a83a800 -> 0x74092af380
05-12 15:19:46.808 23962 23981 D OpenGLRenderer: makeCurrent EglSurface : 0x74092af380 -> 0x737a83a800
05-12 15:19:46.811 23962 23981 D OpenGLRenderer: makeCurrent EglSurface : 0x737a83a800 -> 0x74092af380
05-12 15:19:46.825 23962 23981 D OpenGLRenderer: makeCurrent EglSurface : 0x74092af380 -> 0x737a83a800
05-12 15:19:46.828 23962 23981 D OpenGLRenderer: makeCurrent EglSurface : 0x737a83a800 -> 0x74092af380
05-12 15:19:46.841 23962 23981 D OpenGLRenderer: makeCurrent EglSurface : 0x74092af380 -> 0x737a83a800
05-12 15:19:46.845 23962 23981 D OpenGLRenderer: makeCurrent EglSurface : 0x737a83a800 -> 0x74092af380
05-12 15:19:46.858 23962 23981 D OpenGLRenderer: makeCurrent EglSurface : 0x74092af380 -> 0x737a83a800
05-12 15:19:46.861 23962 23981 D OpenGLRenderer: makeCurrent EglSurface : 0x737a83a800 -> 0x74092af380
05-12 15:19:46.876 23962 23981 D OpenGLRenderer: makeCurrent EglSurface : 0x74092af380 -> 0x737a83a800
05-12 15:19:46.879 23962 23981 D OpenGLRenderer: makeCurrent EglSurface : 0x737a83a800 -> 0x74092af380
05-12 15:19:46.892 23962 23981 D OpenGLRenderer: makeCurrent EglSurface : 0x74092af380 -> 0x737a83a800
05-12 15:19:46.896 23962 23981 D OpenGLRenderer: makeCurrent EglSurface : 0x737a83a800 -> 0x74092af380
05-12 15:19:46.909 23962 23981 D OpenGLRenderer: makeCurrent EglSurface : 0x74092af380 -> 0x737a83a800
05-12 15:19:46.913 23962 23981 D OpenGLRenderer: makeCurrent EglSurface : 0x737a83a800 -> 0x74092af380
05-12 15:19:46.926 23962 23981 D OpenGLRenderer: makeCurrent EglSurface : 0x74092af380 -> 0x737a83a800
05-12 15:19:46.931 23962 23981 D OpenGLRenderer: makeCurrent EglSurface : 0x737a83a800 -> 0x74092af380
05-12 15:19:46.942 23962 23981 D OpenGLRenderer: makeCurrent EglSurface : 0x74092af380 -> 0x737a83a800
05-12 15:19:46.947 23962 23981 D OpenGLRenderer: makeCurrent EglSurface : 0x737a83a800 -> 0x74092af380
05-12 15:19:47.076 23962 23962 D ViewRootImpl: updatePointerIcon pointerType = 10121, calling pid = 23962
05-12 15:19:47.077 23962 23962 D InputManager: setPointerIconType iconId = 10121, callingPid = 23962
05-12 15:19:47.079 23962 23981 D OpenGLRenderer: makeCurrent EglSurface : 0x74092af380 -> 0x737a83a800
05-12 15:19:50.347 23962 23962 W VelocityTracker: division by 0 when computing velocity, Sxx=0.000008, Sx2x2=0.000000, Sxx2=-0.000000
05-12 15:19:50.347 23962 23962 W VelocityTracker: division by 0 when computing velocity, Sxx=0.000008, Sx2x2=0.000000, Sxx2=-0.000000
05-12 15:19:50.830 23962 23962 D ViewRootImpl@89b0b8[PopupWindow:f79615]: ViewPostIme pointer 0
05-12 15:19:50.837 23962 23962 D ViewRootImpl@89b0b8[PopupWindow:f79615]: Relayout returned: old=(1658,48,1916,576) new=(1658,48,1916,576) req=(258,528)0 dur=5 res=0x1 s={true 495738212352} ch=false
05-12 15:19:50.840 23962 23962 D ViewRootImpl@7753dda[bVNC]: MSG_WINDOW_FOCUS_CHANGED 1 1
05-12 15:19:50.840 23962 23962 D InputMethodManager: prepareNavigationBarInfo() DecorView@97a79ca[bVNC]
05-12 15:19:50.840 23962 23962 D InputMethodManager: getNavigationBarColor() -855310
05-12 15:19:50.847 23962 23962 D ViewRootImpl@89b0b8[PopupWindow:f79615]: MSG_WINDOW_FOCUS_CHANGED 0 1
05-12 15:19:50.852 23962 23981 D OpenGLRenderer: makeCurrent EglSurface : 0x737a83a800 -> 0x74092af380
05-12 15:19:50.865 23962 23981 D OpenGLRenderer: makeCurrent EglSurface : 0x74092af380 -> 0x737a83a800
05-12 15:19:50.896 23962 23962 D ViewRootImpl@89b0b8[PopupWindow:f79615]: ViewPostIme pointer 1
05-12 15:19:50.897 23962 23962 D ViewRootImpl: updatePointerIcon pointerType = 10121, calling pid = 23962
05-12 15:19:50.897 23962 23962 D InputManager: setPointerIconType iconId = 10121, callingPid = 23962
05-12 15:19:51.032 23962 23962 D ViewRootImpl: updatePointerIcon pointerType = 1002, calling pid = 23962
05-12 15:19:51.033 23962 23962 D InputManager: setPointerIconType iconId = 1002, callingPid = 23962
05-12 15:19:51.035 23962 23981 D OpenGLRenderer: makeCurrent EglSurface : 0x737a83a800 -> 0x74092af380
05-12 15:19:51.039 23962 23981 D OpenGLRenderer: makeCurrent EglSurface : 0x74092af380 -> 0x737a83a800
05-12 15:19:51.051 23962 23981 D OpenGLRenderer: makeCurrent EglSurface : 0x737a83a800 -> 0x74092af380
05-12 15:19:51.066 23962 23981 D OpenGLRenderer: makeCurrent EglSurface : 0x74092af380 -> 0x737a83a800
05-12 15:19:51.068 23962 23981 D OpenGLRenderer: makeCurrent EglSurface : 0x737a83a800 -> 0x74092af380
05-12 15:19:51.083 23962 23981 D OpenGLRenderer: makeCurrent EglSurface : 0x74092af380 -> 0x737a83a800
05-12 15:19:51.085 23962 23981 D OpenGLRenderer: makeCurrent EglSurface : 0x737a83a800 -> 0x74092af380
05-12 15:19:51.100 23962 23981 D OpenGLRenderer: makeCurrent EglSurface : 0x74092af380 -> 0x737a83a800
05-12 15:19:51.103 23962 23981 D OpenGLRenderer: makeCurrent EglSurface : 0x737a83a800 -> 0x74092af380
05-12 15:19:51.116 23962 23981 D OpenGLRenderer: makeCurrent EglSurface : 0x74092af380 -> 0x737a83a800
05-12 15:19:51.119 23962 23981 D OpenGLRenderer: makeCurrent EglSurface : 0x737a83a800 -> 0x74092af380
05-12 15:19:51.132 23962 23981 D OpenGLRenderer: makeCurrent EglSurface : 0x74092af380 -> 0x737a83a800
05-12 15:19:51.151 23962 23981 D OpenGLRenderer: makeCurrent EglSurface : 0x737a83a800 -> 0x0
05-12 15:19:51.151 23962 23981 D OpenGLRenderer: destroyEglSurface : 0x737a83a800
05-12 15:19:51.151 23962 23981 I mali_egl: eglDestroySurface() in
05-12 15:19:51.153 23962 23981 I mali_winsys: delete_surface() [322x592] return
05-12 15:19:51.153 23962 23981 I mali_egl: eglDestroySurface() out
05-12 15:19:51.154 23962 23981 W libEGL  : EGLNativeWindowType 0x730745c1d0 disconnect failed
05-12 15:19:51.154 23962 23981 D OpenGLRenderer: ~ReliableSurface : 0x730745c1c0
05-12 15:19:51.154 23962 23962 D ViewRootImpl@89b0b8[PopupWindow:f79615]: dispatchDetachedFromWindow
05-12 15:19:51.160 23962 23962 D InputTransport: Input channel destroyed: '8a3c534', fd=71
05-12 15:19:51.462 23962 23962 D ViewRootImpl@7753dda[bVNC]: ViewPostIme pointer 0
05-12 15:19:51.465 23962 23962 D ViewRootImpl: updatePointerIcon pointerType = 1002, calling pid = 23962
05-12 15:19:51.465 23962 23962 D InputManager: setPointerIconType iconId = 1002, callingPid = 23962
05-12 15:19:51.467 23962 23981 D OpenGLRenderer: makeCurrent EglSurface : 0x0 -> 0x74092af380
05-12 15:19:51.580 23962 23962 D ViewRootImpl@7753dda[bVNC]: ViewPostIme pointer 1
05-12 15:19:51.581 23962 23962 D ViewRootImpl: updatePointerIcon pointerType = 1002, calling pid = 23962
05-12 15:19:51.581 23962 23962 D InputManager: setPointerIconType iconId = 1002, callingPid = 23962
05-12 15:19:51.654 23962 23962 D Toast   : show: focusDisplayId = 2, isFocusInDesktop = true mCustomDisplayId=-1
05-12 15:19:51.659 23962 23979 V Toast   : SHOW: android.widget.Toast$TN@61073df
05-12 15:19:51.660 23962 23962 V Toast   : HANDLE SHOW: android.widget.Toast$TN@61073df mView=null mNextView=android.widget.LinearLayout{9a0d88a V.E...... ......I. 0,0-0,0}
05-12 15:19:51.660 23962 23962 V Toast   : HANDLE HIDE: android.widget.Toast$TN@61073df mView=null
05-12 15:19:51.665 23962 23962 D ViewRootImpl@249971[Toast]: setView = android.widget.LinearLayout@9a0d88a TM=true MM=false
05-12 15:19:51.665 23962 23962 V Toast   : Text: Mogc in android.widget.Toast$TN@61073df
05-12 15:19:51.673 23962 23962 D ViewRootImpl@249971[Toast]: Relayout returned: old=(0,0,1920,1018) new=(579,910,1341,954) req=(762,44)0 dur=5 res=0x7 s={true 494043443200} ch=true
05-12 15:19:51.673 23962 23981 D OpenGLRenderer: createReliableSurface : 0x730745c080(0x730748b000)
05-12 15:19:51.674 23962 23981 I mali_winsys: new_window_surface() [762x44] return: 0x3000
05-12 15:19:51.674 23962 23981 D OpenGLRenderer: makeCurrent EglSurface : 0x74092af380 -> 0x736c59cd80
05-12 15:19:51.692 23962 23981 D OpenGLRenderer: makeCurrent EglSurface : 0x736c59cd80 -> 0x74092af380
05-12 15:19:51.699 23962 23962 D ViewRootImpl@249971[Toast]: MSG_RESIZED: frame=(579,910,1341,954) ci=(0,0,0,0) vi=(0,0,762,44) or=2
05-12 15:19:51.967 23962 23962 D ViewRootImpl: updatePointerIcon pointerType = 10121, calling pid = 23962
05-12 15:19:51.967 23962 23962 D InputManager: setPointerIconType iconId = 10121, callingPid = 23962
05-12 15:19:52.969 23962 23962 W VelocityTracker: division by 0 when computing velocity, Sxx=0.000015, Sx2x2=0.000000, Sxx2=-0.000000
05-12 15:19:52.969 23962 23962 W VelocityTracker: division by 0 when computing velocity, Sxx=0.000015, Sx2x2=0.000000, Sxx2=-0.000000
05-12 15:19:54.854 23962 23962 D ViewRootImpl@7753dda[bVNC]: MSG_WINDOW_FOCUS_CHANGED 0 1
05-12 15:19:54.854 23962 23962 D InputMethodManager: prepareNavigationBarInfo() DecorView@97a79ca[bVNC]
05-12 15:19:54.854 23962 23962 D InputMethodManager: getNavigationBarColor() -855310
05-12 15:19:54.901 23962 23962 D InputTransport: Input channel destroyed: 'ClientS', fd=67
05-12 15:19:55.159 23962 24003 V Toast   : HIDE: android.widget.Toast$TN@61073df
05-12 15:19:55.159 23962 23962 V Toast   : HANDLE HIDE: android.widget.Toast$TN@61073df mView=android.widget.LinearLayout{9a0d88a V.E...... ........ 0,0-762,44}
05-12 15:19:55.159 23962 23962 V Toast   : REMOVE! android.widget.LinearLayout{9a0d88a V.E...... ........ 0,0-762,44} in android.widget.Toast$TN@61073df
05-12 15:19:55.160 23962 23981 D OpenGLRenderer: destroyEglSurface : 0x736c59cd80
05-12 15:19:55.160 23962 23981 I mali_egl: eglDestroySurface() in
05-12 15:19:55.161 23962 23981 I mali_winsys: delete_surface() [762x44] return
05-12 15:19:55.161 23962 23981 I mali_egl: eglDestroySurface() out
05-12 15:19:55.161 23962 23981 W libEGL  : EGLNativeWindowType 0x730745c090 disconnect failed
05-12 15:19:55.161 23962 23981 D OpenGLRenderer: ~ReliableSurface : 0x730745c080
05-12 15:19:55.161 23962 23962 D ViewRootImpl@249971[Toast]: dispatchDetachedFromWindow
05-12 15:19:55.173 23962 23962 D InputTransport: Input channel destroyed: 'ab5d339', fd=71
05-12 15:19:56.052 23962 23962 D ViewRootImpl@7753dda[bVNC]: MSG_WINDOW_FOCUS_CHANGED 1 1
05-12 15:19:56.052 23962 23962 D InputMethodManager: prepareNavigationBarInfo() DecorView@97a79ca[bVNC]
05-12 15:19:56.052 23962 23962 D InputMethodManager: getNavigationBarColor() -855310
05-12 15:19:56.059 23962 23962 D InputMethodManager: prepareNavigationBarInfo() DecorView@97a79ca[bVNC]
05-12 15:19:56.059 23962 23962 D InputMethodManager: getNavigationBarColor() -855310
05-12 15:19:56.059 23962 23962 V InputMethodManager: Starting input: tba=com.iiordanov.freebVNC ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
05-12 15:19:56.059 23962 23962 D InputMethodManager: startInputInner - Id : 2
05-12 15:19:56.059 23962 23962 I InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
05-12 15:19:59.532 23962 23962 I MainConfiguration: onPause called
05-12 15:19:59.556 23962 23962 D DecorCaptionView: updateButtonVisibility densityDpi = 160
05-12 15:19:59.582 23962 23962 D InputMethodManager: prepareNavigationBarInfo() DecorView@97a79ca[bVNC]
05-12 15:19:59.582 23962 23962 D InputMethodManager: getNavigationBarColor() -855310
05-12 15:19:59.587 23962 23962 D ViewRootImpl@7753dda[bVNC]: MSG_WINDOW_FOCUS_CHANGED 0 1
05-12 15:19:59.599 23962 23981 D OpenGLRenderer: makeCurrent EglSurface : 0x74092af380 -> 0x0
05-12 15:19:59.599 23962 23981 D OpenGLRenderer: destroyEglSurface : 0x74092af380
05-12 15:19:59.599 23962 23981 I mali_egl: eglDestroySurface() in
05-12 15:19:59.601 23962 23981 I mali_winsys: delete_surface() [1920x1080] return
05-12 15:19:59.601 23962 23981 I mali_egl: eglDestroySurface() out
05-12 15:19:59.602 23962 23981 W libEGL  : EGLNativeWindowType 0x740926ff90 disconnect failed
05-12 15:19:59.602 23962 23981 D OpenGLRenderer: ~ReliableSurface : 0x740926ff80
05-12 15:19:59.605 23962 23962 D ViewRootImpl@7753dda[bVNC]: Relayout returned: old=(0,0,1920,1080) new=(0,0,1920,1080) req=(1920,1080)8 dur=3 res=0x5 s={false 0} ch=true
05-12 15:19:59.624 23962 23962 D ViewRootImpl@7753dda[bVNC]: stopped(true) old=false
05-12 15:19:59.624 23962 23962 I MainConfiguration: onStop called
05-12 15:19:59.707 23962 23962 D InputTransport: Input channel destroyed: 'ClientS', fd=67
05-12 15:21:02.135 23962 23962 D ViewRootImpl@7753dda[bVNC]: Relayout returned: old=(0,0,1920,1080) new=(0,0,1920,1080) req=(1920,1080)4 dur=18 res=0x1 s={false 0} ch=false
05-12 15:21:02.135 23962 23962 D ViewRootImpl@7753dda[bVNC]: stopped(false) old=true
05-12 15:21:02.136 23962 23962 I MainConfiguration: onStart called
05-12 15:21:02.137 23962 23962 D DecorCaptionView: updateButtonVisibility densityDpi = 160
05-12 15:21:02.137 23962 23962 D ViewRootImpl@7753dda[bVNC]: stopped(false) old=false
05-12 15:21:02.137 23962 23962 I MainConfiguration: onResume called
05-12 15:21:02.137 23962 23962 I MainConfiguration: onResumeFragments called
05-12 15:21:02.138 23962 23962 I MainConfiguration: arriveOnPage called
05-12 15:21:02.159 23962 23962 D Dialog  : mIsSamsungBasicInteraction = false
05-12 15:21:02.159 23962 23962 D Dialog  : mIsSamsungBasicInteraction = false, isMetaDataInActivity = false
05-12 15:21:02.161 23962 23962 I MultiWindowDecorSupport: [INFO] WindowingMode = 1, DecorView = DecorView@4bbdfd5[]
05-12 15:21:02.161 23962 23962 I MultiWindowDecorSupport: updateCaptionType >> DecorView@4bbdfd5[], isFloating: true, isApplication: true, hasWindowDecorCaption: true, hasWindowControllerCallback: false
05-12 15:21:02.161 23962 23962 D MultiWindowDecorSupport: setCaptionType = 0, DecorView = DecorView@4bbdfd5[]
05-12 15:21:02.171 23962 23962 D DecorView: It doesn't generate decor captions because the app has abnormally created a decor view.
05-12 15:21:02.173 23962 23962 D ViewRootImpl@d947623[bVNC: Intuitive, secure VNC client]: setView = com.android.internal.policy.DecorView@4bbdfd5 TM=true MM=false
05-12 15:21:02.181 23962 23962 D ViewRootImpl@7753dda[bVNC]: Relayout returned: old=(0,0,1920,1080) new=(0,0,1920,1080) req=(1920,1080)0 dur=5 res=0x7 s={true 494043443200} ch=true
05-12 15:21:02.181 23962 23981 D OpenGLRenderer: createReliableSurface : 0x740926f1c0(0x730748b000)
05-12 15:21:02.182 23962 23981 I mali_winsys: new_window_surface() [1920x1080] return: 0x3000
05-12 15:21:02.184 23962 23981 D OpenGLRenderer: makeCurrent EglSurface : 0x0 -> 0x74092af380
05-12 15:21:02.203 23962 23962 D ViewRootImpl@d947623[bVNC: Intuitive, secure VNC client]: Relayout returned: old=(0,0,1920,1018) new=(0,0,1920,1018) req=(1920,1018)0 dur=4 res=0x7 s={true 494043668480} ch=true
05-12 15:21:02.203 23962 23981 D OpenGLRenderer: createReliableSurface : 0x730745a000(0x73074c2000)
05-12 15:21:02.204 23962 23981 I mali_winsys: new_window_surface() [1920x1018] return: 0x3000
05-12 15:21:02.205 23962 23962 E DecorView: mWindow.mActivityCurrentConfig is null
05-12 15:21:02.210 23962 23981 D OpenGLRenderer: makeCurrent EglSurface : 0x74092af380 -> 0x736c3b5300
05-12 15:21:02.244 23962 23981 D OpenGLRenderer: makeCurrent EglSurface : 0x736c3b5300 -> 0x74092af380
05-12 15:21:02.245 23962 23962 D ViewRootImpl@d947623[bVNC: Intuitive, secure VNC client]: MSG_WINDOW_FOCUS_CHANGED 1 1
05-12 15:21:02.245 23962 23962 D InputMethodManager: prepareNavigationBarInfo() DecorView@4bbdfd5[bVNC: Intuitive, secure VNC client]
05-12 15:21:02.245 23962 23962 D InputMethodManager: getNavigationBarColor() -855310
05-12 15:21:02.246 23962 23962 D InputMethodManager: prepareNavigationBarInfo() DecorView@4bbdfd5[bVNC: Intuitive, secure VNC client]
05-12 15:21:02.246 23962 23962 D InputMethodManager: getNavigationBarColor() -855310
05-12 15:21:02.246 23962 23962 V InputMethodManager: Starting input: tba=com.iiordanov.freebVNC ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
05-12 15:21:02.246 23962 23962 D InputMethodManager: startInputInner - Id : 2
05-12 15:21:02.246 23962 23962 I InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
05-12 15:21:02.260 23962 23962 D ViewRootImpl@d947623[bVNC: Intuitive, secure VNC client]: MSG_RESIZED: frame=(0,0,1920,1018) ci=(0,0,0,0) vi=(0,0,0,0) or=2
05-12 15:21:02.262 23962 23981 D OpenGLRenderer: makeCurrent EglSurface : 0x74092af380 -> 0x736c3b5300
05-12 15:21:02.371 23962 23962 D ViewRootImpl: updatePointerIcon pointerType = 10121, calling pid = 23962
05-12 15:21:02.371 23962 23962 D InputManager: setPointerIconType iconId = 10121, callingPid = 23962
05-12 15:21:03.233 23962 23962 D ViewRootImpl: updatePointerIcon pointerType = 1002, calling pid = 23962
05-12 15:21:03.235 23962 23962 D InputManager: setPointerIconType iconId = 1002, callingPid = 23962
05-12 15:21:03.448 23962 23962 D ViewRootImpl@d947623[bVNC: Intuitive, secure VNC client]: ViewPostIme pointer 0
05-12 15:21:03.450 23962 23962 D ViewRootImpl: updatePointerIcon pointerType = 1002, calling pid = 23962
05-12 15:21:03.451 23962 23962 D InputManager: setPointerIconType iconId = 1002, callingPid = 23962
05-12 15:21:03.555 23962 23962 D ViewRootImpl@d947623[bVNC: Intuitive, secure VNC client]: ViewPostIme pointer 1
05-12 15:21:03.555 23962 23962 D ViewRootImpl: updatePointerIcon pointerType = 1002, calling pid = 23962
05-12 15:21:03.555 23962 23962 D InputManager: setPointerIconType iconId = 1002, callingPid = 23962
05-12 15:21:03.573 23962 23981 D OpenGLRenderer: makeCurrent EglSurface : 0x736c3b5300 -> 0x0
05-12 15:21:03.573 23962 23981 D OpenGLRenderer: destroyEglSurface : 0x736c3b5300
05-12 15:21:03.573 23962 23981 I mali_egl: eglDestroySurface() in
05-12 15:21:03.575 23962 23981 I mali_winsys: delete_surface() [1920x1018] return
05-12 15:21:03.575 23962 23981 I mali_egl: eglDestroySurface() out
05-12 15:21:03.575 23962 23981 W libEGL  : EGLNativeWindowType 0x730745a010 disconnect failed
05-12 15:21:03.575 23962 23981 D OpenGLRenderer: ~ReliableSurface : 0x730745a000
05-12 15:21:03.575 23962 23981 D OpenGLRenderer: endAllActiveAnimators on 0x72fb051300 (RippleDrawable) with handle 0x737a750960
05-12 15:21:03.575 23962 23962 D ViewRootImpl@d947623[bVNC: Intuitive, secure VNC client]: dispatchDetachedFromWindow
05-12 15:21:03.581 23962 23962 D InputTransport: Input channel destroyed: '8e9102c', fd=67
--------- beginning of system
05-12 15:21:03.582 23962 23962 W ViewRootImpl@d947623[bVNC: Intuitive, secure VNC client]: Dropping event due to root view being removed: 
05-12 15:21:03.582 23962 23962 E ViewRootImpl@d947623[bVNC: Intuitive, secure VNC client]: mStopped=false mHasWindowFocus=true mPausedForTransition=false
05-12 15:21:03.582 23962 23962 W InputEventReceiver: Attempted to finish an input event but the input event receiver has already been disposed.
05-12 15:21:03.582 23962 23962 W ViewRootImpl@d947623[bVNC: Intuitive, secure VNC client]: Dropping event due to root view being removed: 
05-12 15:21:03.582 23962 23962 E ViewRootImpl@d947623[bVNC: Intuitive, secure VNC client]: mStopped=false mHasWindowFocus=true mPausedForTransition=false
05-12 15:21:03.582 23962 23962 W InputEventReceiver: Attempted to finish an input event but the input event receiver has already been disposed.
05-12 15:21:03.586 23962 23962 D ViewRootImpl@7753dda[bVNC]: MSG_WINDOW_FOCUS_CHANGED 1 1
05-12 15:21:03.586 23962 23962 D InputMethodManager: prepareNavigationBarInfo() DecorView@97a79ca[bVNC]
05-12 15:21:03.586 23962 23962 D InputMethodManager: getNavigationBarColor() -855310
05-12 15:21:03.593 23962 23962 D InputMethodManager: prepareNavigationBarInfo() DecorView@97a79ca[bVNC]
05-12 15:21:03.593 23962 23962 D InputMethodManager: getNavigationBarColor() -855310
05-12 15:21:03.593 23962 23962 V InputMethodManager: Starting input: tba=com.iiordanov.freebVNC ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
05-12 15:21:03.593 23962 23962 D InputMethodManager: startInputInner - Id : 2
05-12 15:21:03.593 23962 23962 I InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
05-12 15:21:03.596 23962 23962 D InputTransport: Input channel destroyed: 'ClientS', fd=72
05-12 15:21:03.601 23962 23981 D OpenGLRenderer: makeCurrent EglSurface : 0x0 -> 0x74092af380
05-12 15:21:03.601 23962 23962 E ViewRootImpl: sendUserActionEvent() mView returned.
05-12 15:21:03.670 23962 23962 D ViewRootImpl: updatePointerIcon pointerType = 10121, calling pid = 23962
05-12 15:21:03.670 23962 23962 D InputManager: setPointerIconType iconId = 10121, callingPid = 23962
05-12 15:21:05.084 23962 23962 D ViewRootImpl: updatePointerIcon pointerType = 1008, calling pid = 23962
05-12 15:21:05.084 23962 23962 D InputManager: setPointerIconType iconId = 1008, callingPid = 23962
05-12 15:21:05.300 23962 23962 D ViewRootImpl: updatePointerIcon pointerType = 10121, calling pid = 23962
05-12 15:21:05.300 23962 23962 D InputManager: setPointerIconType iconId = 10121, callingPid = 23962
05-12 15:21:05.334 23962 23962 D ViewRootImpl: updatePointerIcon pointerType = 1008, calling pid = 23962
05-12 15:21:05.335 23962 23962 D InputManager: setPointerIconType iconId = 1008, callingPid = 23962
05-12 15:21:05.401 23962 23962 D ViewRootImpl: updatePointerIcon pointerType = 1002, calling pid = 23962
05-12 15:21:05.401 23962 23962 D InputManager: setPointerIconType iconId = 1002, callingPid = 23962
05-12 15:21:05.433 23962 23962 D ViewRootImpl: updatePointerIcon pointerType = 10121, calling pid = 23962
05-12 15:21:05.434 23962 23962 D InputManager: setPointerIconType iconId = 10121, callingPid = 23962
05-12 15:21:05.717 23962 23962 W VelocityTracker: division by 0 when computing velocity, Sxx=0.000004, Sx2x2=0.000000, Sxx2=-0.000000
05-12 15:21:05.717 23962 23962 W VelocityTracker: division by 0 when computing velocity, Sxx=0.000004, Sx2x2=0.000000, Sxx2=-0.000000
05-12 15:21:05.752 23962 23962 D ViewRootImpl: updatePointerIcon pointerType = 1002, calling pid = 23962
05-12 15:21:05.752 23962 23962 D InputManager: setPointerIconType iconId = 1002, callingPid = 23962
05-12 15:21:06.520 23962 23962 D ViewRootImpl@7753dda[bVNC]: ViewPostIme pointer 0
05-12 15:21:06.520 23962 23962 D ViewRootImpl: updatePointerIcon pointerType = 1002, calling pid = 23962
05-12 15:21:06.521 23962 23962 D InputManager: setPointerIconType iconId = 1002, callingPid = 23962
05-12 15:21:06.643 23962 23962 D ViewRootImpl@7753dda[bVNC]: ViewPostIme pointer 1
05-12 15:21:06.643 23962 23962 D ViewRootImpl: updatePointerIcon pointerType = 1002, calling pid = 23962
05-12 15:21:06.643 23962 23962 D InputManager: setPointerIconType iconId = 1002, callingPid = 23962
05-12 15:21:06.669 23962 23962 I MainConfiguration: onPause called
05-12 15:21:06.679 23962 23962 D DecorCaptionView: updateButtonVisibility densityDpi = 160
05-12 15:21:06.701 23962 23962 I MultiWindowDecorSupport: [INFO] WindowingMode = 1, DecorView = DecorView@bd60474[]
05-12 15:21:06.701 23962 23962 I MultiWindowDecorSupport: updateCaptionType >> DecorView@bd60474[], isApplicationType: true, isDexCompatEnabled: false, isDecorCaptionWindow: false, hasContainer: true
05-12 15:21:06.701 23962 23962 I MultiWindowDecorSupport: updateCaptionType >> DecorView@bd60474[], isFloating: false, isApplication: true, hasWindowDecorCaption: true, hasWindowControllerCallback: true
05-12 15:21:06.701 23962 23962 D MultiWindowDecorSupport: setCaptionType = 1, DecorView = DecorView@bd60474[]
05-12 15:21:06.701 23962 23962 D DecorView: inflateDecorCaptionView: APPCTX_DPI=160, CTX_DPI=160
05-12 15:21:06.701 23962 23962 D DecorView: getAdaptedContext: Final densityDpi = 160
05-12 15:21:06.703 23962 23962 D DecorCaptionView: updateButtonVisibility densityDpi = 160
05-12 15:21:06.705 23962 23962 D DecorCaptionView: updateButtonVisibility densityDpi = 160
05-12 15:21:06.711 23962 23962 D Dialog  : mIsSamsungBasicInteraction = false
05-12 15:21:06.711 23962 23962 D Dialog  : mIsSamsungBasicInteraction = false, isMetaDataInActivity = false
05-12 15:21:06.718 23962 23962 I MultiWindowDecorSupport: [INFO] WindowingMode = 1, DecorView = DecorView@a8f1304[Connecting…]
05-12 15:21:06.718 23962 23962 I MultiWindowDecorSupport: updateCaptionType >> DecorView@a8f1304[Connecting…], isFloating: true, isApplication: true, hasWindowDecorCaption: true, hasWindowControllerCallback: false
05-12 15:21:06.718 23962 23962 D MultiWindowDecorSupport: setCaptionType = 0, DecorView = DecorView@a8f1304[Connecting…]
05-12 15:21:06.722 23962 23962 D ScrollView: initGoToTop
05-12 15:21:06.723 23962 23962 D ScrollView: initGoToTop
05-12 15:21:06.729 23962 23962 D DecorView: It doesn't generate decor captions because the app has abnormally created a decor view.
05-12 15:21:06.732 23962 23962 D ViewRootImpl@7a8b007[Connecting…]: setView = com.android.internal.policy.DecorView@a8f1304 TM=true MM=false
05-12 15:21:06.740 23962 23962 D AndroidRuntime: Shutting down VM
05-12 15:21:06.741 23962 23962 E AndroidRuntime: FATAL EXCEPTION: main
05-12 15:21:06.741 23962 23962 E AndroidRuntime: Process: com.iiordanov.freebVNC, PID: 23962
05-12 15:21:06.741 23962 23962 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.iiordanov.freebVNC/com.iiordanov.bVNC.RemoteCanvasActivity}: java.lang.NullPointerException: Attempt to read from field 'boolean com.iiordanov.bVNC.RemoteCanvas.isOpaque' on a null object reference
05-12 15:21:06.741 23962 23962 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3555)
05-12 15:21:06.741 23962 23962 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3707)
05-12 15:21:06.741 23962 23962 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
05-12 15:21:06.741 23962 23962 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
05-12 15:21:06.741 23962 23962 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
05-12 15:21:06.741 23962 23962 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2220)
05-12 15:21:06.741 23962 23962 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
05-12 15:21:06.741 23962 23962 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:237)
05-12 15:21:06.741 23962 23962 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8016)
05-12 15:21:06.741 23962 23962 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-12 15:21:06.741 23962 23962 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
05-12 15:21:06.741 23962 23962 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
05-12 15:21:06.741 23962 23962 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to read from field 'boolean com.iiordanov.bVNC.RemoteCanvas.isOpaque' on a null object reference
05-12 15:21:06.741 23962 23962 E AndroidRuntime: 	at com.iiordanov.bVNC.RemoteCanvasActivity.onCreate(RemoteCanvasActivity.java:280)
05-12 15:21:06.741 23962 23962 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7957)
05-12 15:21:06.741 23962 23962 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7946)
05-12 15:21:06.741 23962 23962 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
05-12 15:21:06.741 23962 23962 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3530)
05-12 15:21:06.741 23962 23962 E AndroidRuntime: 	... 11 more
05-12 15:21:06.756 23962 23962 I Process : Sending signal. PID: 23962 SIG: 9
05-12 15:21:12.140 26547 26547 E rdanov.freebVN: Not starting debugger since process cannot load the jdwp agent.
05-12 15:21:12.146 26547 26547 D ActivityThread: setConscryptValidator
05-12 15:21:12.146 26547 26547 D ActivityThread: setConscryptValidator - put
05-12 15:21:12.186 26566 26566 E rdanov.freebVN: Not starting debugger since process cannot load the jdwp agent.
05-12 15:21:12.191 26566 26566 D ActivityThread: setConscryptValidator
05-12 15:21:12.191 26566 26566 D ActivityThread: setConscryptValidator - put
05-12 15:21:12.243 26566 26566 I MultiWindowDecorSupport: [INFO] WindowingMode = 1, DecorView = DecorView@97a79ca[]
05-12 15:21:12.243 26566 26566 I MultiWindowDecorSupport: updateCaptionType >> DecorView@97a79ca[], isApplicationType: true, isDexCompatEnabled: false, isDecorCaptionWindow: false, hasContainer: true
05-12 15:21:12.243 26566 26566 I MultiWindowDecorSupport: updateCaptionType >> DecorView@97a79ca[], isFloating: false, isApplication: true, hasWindowDecorCaption: true, hasWindowControllerCallback: true
05-12 15:21:12.243 26566 26566 D MultiWindowDecorSupport: setCaptionType = 1, DecorView = DecorView@97a79ca[]
05-12 15:21:12.243 26566 26566 D DecorView: inflateDecorCaptionView: APPCTX_DPI=160, CTX_DPI=160
05-12 15:21:12.243 26566 26566 D DecorView: getAdaptedContext: Final densityDpi = 160
05-12 15:21:12.248 26566 26566 D DecorCaptionView: updateButtonVisibility densityDpi = 160
05-12 15:21:12.252 26566 26566 D DecorCaptionView: updateButtonVisibility densityDpi = 160
05-12 15:21:12.256 26566 26566 D ScrollView: initGoToTop
05-12 15:21:12.278 26566 26566 I GetTextFragment: newInstance called
05-12 15:21:12.278 26566 26566 I GetTextFragment: newInstance called
05-12 15:21:12.279 26566 26566 D PermissionsManager: [android.permission.INTERNET, android.permission.VIBRATE, android.permission.ACCESS_NETWORK_STATE, android.permission.READ_EXTERNAL_STORAGE, android.permission.WRITE_EXTERNAL_STORAGE, android.permission.ACCESS_MEDIA_LOCATION]
05-12 15:21:12.280 26566 26566 I MainConfiguration: onStart called
05-12 15:21:12.281 26566 26566 D DecorCaptionView: updateButtonVisibility densityDpi = 160
05-12 15:21:12.281 26566 26566 I MainConfiguration: onResume called
05-12 15:21:12.281 26566 26566 I MainConfiguration: onResumeFragments called
05-12 15:21:12.283 26566 26566 I MainConfiguration: arriveOnPage called
05-12 15:21:12.289 26566 26566 E ConnectionBean: Failed to query default input method, context is null.
05-12 15:21:12.294 26566 26566 D Dialog  : mIsSamsungBasicInteraction = false
05-12 15:21:12.294 26566 26566 D Dialog  : mIsSamsungBasicInteraction = false, isMetaDataInActivity = false
05-12 15:21:12.295 26566 26566 I MultiWindowDecorSupport: [INFO] WindowingMode = 1, DecorView = DecorView@4b9824b[]
05-12 15:21:12.295 26566 26566 I MultiWindowDecorSupport: updateCaptionType >> DecorView@4b9824b[], isFloating: true, isApplication: true, hasWindowDecorCaption: true, hasWindowControllerCallback: false
05-12 15:21:12.295 26566 26566 D MultiWindowDecorSupport: setCaptionType = 0, DecorView = DecorView@4b9824b[]
05-12 15:21:12.303 26566 26566 D DecorView: It doesn't generate decor captions because the app has abnormally created a decor view.
05-12 15:21:12.305 26566 26566 D ViewRootImpl@8dbc2ce[bVNC: Intuitive, secure VNC client]: setView = com.android.internal.policy.DecorView@4b9824b TM=true MM=false
05-12 15:21:12.307 26566 26566 D ViewRootImpl@7753dda[bVNC]: setView = com.android.internal.policy.DecorView@97a79ca TM=true MM=false
05-12 15:21:12.321 26566 26566 D ViewRootImpl@8dbc2ce[bVNC: Intuitive, secure VNC client]: Relayout returned: old=(0,0,1920,1018) new=(0,0,1920,1018) req=(1920,1018)0 dur=4 res=0x7 s={true 494225473536} ch=true
05-12 15:21:12.321 26566 26586 D OpenGLRenderer: createReliableSurface : 0x737601bbc0(0x7312224000)
05-12 15:21:12.327 26566 26586 D OpenGLRenderer: makeCurrent EglSurface : 0x0 -> 0x0
05-12 15:21:12.332 26566 26586 I mali_winsys: new_window_surface() [1920x1018] return: 0x3000
05-12 15:21:12.333 26566 26566 E DecorView: mWindow.mActivityCurrentConfig is null
05-12 15:21:12.336 26566 26586 D OpenGLRenderer: makeCurrent EglSurface : 0x0 -> 0x737604f280
05-12 15:21:12.340 26566 26586 W Gralloc3: mapper 3.x is not supported
05-12 15:21:12.344 26566 26586 I gralloc : Arm Module v1.0
05-12 15:21:12.368 26566 26566 D ViewRootImpl@7753dda[bVNC]: Relayout returned: old=(0,0,1920,1080) new=(0,0,1920,1080) req=(1920,1080)0 dur=5 res=0x7 s={true 494225838080} ch=true
05-12 15:21:12.368 26566 26586 D OpenGLRenderer: createReliableSurface : 0x737601c0c0(0x731227d000)
05-12 15:21:12.368 26566 26586 I mali_winsys: new_window_surface() [1920x1080] return: 0x3000
05-12 15:21:12.370 26566 26566 D ScrollView:  onsize change changed 
05-12 15:21:12.374 26566 26586 D OpenGLRenderer: makeCurrent EglSurface : 0x737604f280 -> 0x736c563b80
05-12 15:21:12.392 26566 26566 D ViewRootImpl@8dbc2ce[bVNC: Intuitive, secure VNC client]: MSG_WINDOW_FOCUS_CHANGED 1 1
05-12 15:21:12.393 26566 26566 D InputMethodManager: prepareNavigationBarInfo() DecorView@4b9824b[bVNC: Intuitive, secure VNC client]
05-12 15:21:12.393 26566 26566 D InputMethodManager: getNavigationBarColor() -855310
05-12 15:21:12.393 26566 26566 D InputMethodManager: prepareNavigationBarInfo() DecorView@4b9824b[bVNC: Intuitive, secure VNC client]
05-12 15:21:12.393 26566 26566 D InputMethodManager: getNavigationBarColor() -855310
05-12 15:21:12.393 26566 26566 V InputMethodManager: Starting input: tba=com.iiordanov.freebVNC ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
05-12 15:21:12.393 26566 26566 D InputMethodManager: startInputInner - Id : 2
05-12 15:21:12.393 26566 26566 I InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
05-12 15:21:12.413 26566 26586 D OpenGLRenderer: makeCurrent EglSurface : 0x736c563b80 -> 0x737604f280
05-12 15:21:12.419 26566 26586 D OpenGLRenderer: makeCurrent EglSurface : 0x737604f280 -> 0x736c563b80
05-12 15:21:12.435 26566 26566 D ViewRootImpl@8dbc2ce[bVNC: Intuitive, secure VNC client]: MSG_RESIZED_REPORT: frame=(0,0,1920,1018) ci=(0,0,0,0) vi=(0,0,0,0) or=2
05-12 15:21:12.435 26566 26566 D ViewRootImpl@7753dda[bVNC]: MSG_RESIZED: frame=(0,0,1920,1080) ci=(0,0,0,62) vi=(0,0,0,62) or=2
05-12 15:21:12.435 26566 26566 D ViewRootImpl@8dbc2ce[bVNC: Intuitive, secure VNC client]: MSG_RESIZED: frame=(0,0,1920,1018) ci=(0,0,0,0) vi=(0,0,0,0) or=2
05-12 15:21:12.435 26566 26566 D ViewRootImpl@7753dda[bVNC]: MSG_RESIZED: frame=(0,0,1920,1080) ci=(0,0,0,62) vi=(0,0,0,62) or=2
05-12 15:21:12.435 26566 26566 D InputMethodManager: prepareNavigationBarInfo() DecorView@4b9824b[bVNC: Intuitive, secure VNC client]
05-12 15:21:12.435 26566 26566 D InputMethodManager: getNavigationBarColor() -855310
05-12 15:21:12.435 26566 26566 V InputMethodManager: Starting input: tba=com.iiordanov.freebVNC ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
05-12 15:21:12.435 26566 26566 D InputMethodManager: startInputInner - Id : 2
05-12 15:21:12.445 26566 26586 D OpenGLRenderer: makeCurrent EglSurface : 0x736c563b80 -> 0x737604f280
05-12 15:21:12.455 26566 26586 D OpenGLRenderer: makeCurrent EglSurface : 0x737604f280 -> 0x736c563b80
05-12 15:21:12.926 26566 26566 D ViewRootImpl: updatePointerIcon pointerType = 10121, calling pid = 26566
05-12 15:21:12.927 26566 26566 D InputManager: setPointerIconType iconId = 10121, callingPid = 26566
05-12 15:21:12.933 26566 26586 D OpenGLRenderer: makeCurrent EglSurface : 0x736c563b80 -> 0x737604f280
05-12 15:21:13.666 26566 26566 D ViewRootImpl: updatePointerIcon pointerType = 1002, calling pid = 26566
05-12 15:21:13.667 26566 26566 D InputManager: setPointerIconType iconId = 1002, callingPid = 26566
05-12 15:21:13.832 26566 26566 D ViewRootImpl: updatePointerIcon pointerType = 10121, calling pid = 26566
05-12 15:21:13.832 26566 26566 D InputManager: setPointerIconType iconId = 10121, callingPid = 26566
05-12 15:21:13.840 26566 26566 D ViewRootImpl@8dbc2ce[bVNC: Intuitive, secure VNC client]: ViewPostIme pointer 0
05-12 15:21:13.841 26566 26566 D ViewRootImpl: updatePointerIcon pointerType = 10121, calling pid = 26566
05-12 15:21:13.841 26566 26566 D InputManager: setPointerIconType iconId = 10121, callingPid = 26566
05-12 15:21:13.899 26566 26566 D ViewRootImpl: updatePointerIcon pointerType = 1002, calling pid = 26566
05-12 15:21:13.900 26566 26566 D InputManager: setPointerIconType iconId = 1002, callingPid = 26566
05-12 15:21:13.925 26566 26586 D OpenGLRenderer: makeCurrent EglSurface : 0x737604f280 -> 0x736c563b80
05-12 15:21:13.930 26566 26566 D ViewRootImpl@8dbc2ce[bVNC: Intuitive, secure VNC client]: ViewPostIme pointer 1
05-12 15:21:13.931 26566 26566 D ViewRootImpl: updatePointerIcon pointerType = 1002, calling pid = 26566
05-12 15:21:13.931 26566 26566 D InputManager: setPointerIconType iconId = 1002, callingPid = 26566
05-12 15:21:13.936 26566 26586 D OpenGLRenderer: makeCurrent EglSurface : 0x736c563b80 -> 0x737604f280
05-12 15:21:13.940 26566 26586 D OpenGLRenderer: makeCurrent EglSurface : 0x737604f280 -> 0x736c563b80
05-12 15:21:13.952 26566 26586 D OpenGLRenderer: makeCurrent EglSurface : 0x736c563b80 -> 0x737604f280
05-12 15:21:13.956 26566 26586 D OpenGLRenderer: makeCurrent EglSurface : 0x737604f280 -> 0x736c563b80
05-12 15:21:13.969 26566 26586 D OpenGLRenderer: makeCurrent EglSurface : 0x736c563b80 -> 0x737604f280
05-12 15:21:13.972 26566 26586 D OpenGLRenderer: makeCurrent EglSurface : 0x737604f280 -> 0x736c563b80
05-12 15:21:13.983 26566 26586 D OpenGLRenderer: makeCurrent EglSurface : 0x736c563b80 -> 0x737604f280
05-12 15:21:13.988 26566 26586 D OpenGLRenderer: makeCurrent EglSurface : 0x737604f280 -> 0x736c563b80
05-12 15:21:14.000 26566 26586 D OpenGLRenderer: makeCurrent EglSurface : 0x736c563b80 -> 0x737604f280
05-12 15:21:14.005 26566 26586 D OpenGLRenderer: makeCurrent EglSurface : 0x737604f280 -> 0x736c563b80
05-12 15:21:14.017 26566 26586 D OpenGLRenderer: makeCurrent EglSurface : 0x736c563b80 -> 0x737604f280
05-12 15:21:14.023 26566 26586 D OpenGLRenderer: makeCurrent EglSurface : 0x737604f280 -> 0x736c563b80
05-12 15:21:14.034 26566 26586 D OpenGLRenderer: makeCurrent EglSurface : 0x736c563b80 -> 0x737604f280
05-12 15:21:14.038 26566 26586 D OpenGLRenderer: makeCurrent EglSurface : 0x737604f280 -> 0x736c563b80
05-12 15:21:14.052 26566 26586 D OpenGLRenderer: makeCurrent EglSurface : 0x736c563b80 -> 0x737604f280
05-12 15:21:14.057 26566 26586 D OpenGLRenderer: makeCurrent EglSurface : 0x737604f280 -> 0x736c563b80
05-12 15:21:14.067 26566 26586 D OpenGLRenderer: makeCurrent EglSurface : 0x736c563b80 -> 0x737604f280
05-12 15:21:14.071 26566 26586 D OpenGLRenderer: makeCurrent EglSurface : 0x737604f280 -> 0x736c563b80
05-12 15:21:14.084 26566 26586 D OpenGLRenderer: makeCurrent EglSurface : 0x736c563b80 -> 0x737604f280
05-12 15:21:14.088 26566 26586 D OpenGLRenderer: makeCurrent EglSurface : 0x737604f280 -> 0x736c563b80
05-12 15:21:14.104 26566 26586 D OpenGLRenderer: makeCurrent EglSurface : 0x736c563b80 -> 0x737604f280
05-12 15:21:14.109 26566 26586 D OpenGLRenderer: makeCurrent EglSurface : 0x737604f280 -> 0x736c563b80
05-12 15:21:14.117 26566 26586 D OpenGLRenderer: makeCurrent EglSurface : 0x736c563b80 -> 0x737604f280
05-12 15:21:14.121 26566 26586 D OpenGLRenderer: makeCurrent EglSurface : 0x737604f280 -> 0x736c563b80
05-12 15:21:14.134 26566 26586 D OpenGLRenderer: makeCurrent EglSurface : 0x736c563b80 -> 0x737604f280
05-12 15:21:14.138 26566 26586 D OpenGLRenderer: makeCurrent EglSurface : 0x737604f280 -> 0x736c563b80
05-12 15:21:14.151 26566 26586 D OpenGLRenderer: makeCurrent EglSurface : 0x736c563b80 -> 0x737604f280
05-12 15:21:14.155 26566 26586 D OpenGLRenderer: makeCurrent EglSurface : 0x737604f280 -> 0x736c563b80
05-12 15:21:14.169 26566 26586 D OpenGLRenderer: makeCurrent EglSurface : 0x736c563b80 -> 0x737604f280
05-12 15:21:14.173 26566 26586 D OpenGLRenderer: makeCurrent EglSurface : 0x737604f280 -> 0x736c563b80
05-12 15:21:14.185 26566 26586 D OpenGLRenderer: makeCurrent EglSurface : 0x736c563b80 -> 0x737604f280
05-12 15:21:14.194 26566 26586 D OpenGLRenderer: makeCurrent EglSurface : 0x737604f280 -> 0x736c563b80
05-12 15:21:14.501 26566 26566 D ViewRootImpl@8dbc2ce[bVNC: Intuitive, secure VNC client]: ViewPostIme pointer 0
05-12 15:21:14.502 26566 26566 D ViewRootImpl: updatePointerIcon pointerType = 1002, calling pid = 26566
05-12 15:21:14.502 26566 26566 D InputManager: setPointerIconType iconId = 1002, callingPid = 26566
05-12 15:21:14.516 26566 26586 D OpenGLRenderer: makeCurrent EglSurface : 0x736c563b80 -> 0x737604f280
05-12 15:21:14.621 26566 26566 D ViewRootImpl@8dbc2ce[bVNC: Intuitive, secure VNC client]: ViewPostIme pointer 1
05-12 15:21:14.638 26566 26586 D OpenGLRenderer: makeCurrent EglSurface : 0x737604f280 -> 0x0
05-12 15:21:14.638 26566 26586 D OpenGLRenderer: destroyEglSurface : 0x737604f280
05-12 15:21:14.638 26566 26586 I mali_egl: eglDestroySurface() in
05-12 15:21:14.640 26566 26586 I mali_winsys: delete_surface() [1920x1018] return
05-12 15:21:14.640 26566 26586 I mali_egl: eglDestroySurface() out
05-12 15:21:14.640 26566 26586 W libEGL  : EGLNativeWindowType 0x737601bbd0 disconnect failed
05-12 15:21:14.640 26566 26586 D OpenGLRenderer: ~ReliableSurface : 0x737601bbc0
05-12 15:21:14.640 26566 26586 D OpenGLRenderer: endAllActiveAnimators on 0x731226be00 (RippleDrawable) with handle 0x7306565940
05-12 15:21:14.640 26566 26566 D ViewRootImpl@8dbc2ce[bVNC: Intuitive, secure VNC client]: dispatchDetachedFromWindow
05-12 15:21:14.646 26566 26566 D InputTransport: Input channel destroyed: 'b28363 ', fd=56
05-12 15:21:14.646 26566 26566 D ViewRootImpl@7753dda[bVNC]: MSG_WINDOW_FOCUS_CHANGED 1 1
05-12 15:21:14.646 26566 26566 D InputMethodManager: prepareNavigationBarInfo() DecorView@97a79ca[bVNC]
05-12 15:21:14.646 26566 26566 D InputMethodManager: getNavigationBarColor() -855310
05-12 15:21:14.649 26566 26566 D EmergencyMode: [EmergencyManager] android createPackageContext successful: com.iiordanov.freebVNC
05-12 15:21:14.656 26566 26566 D InputMethodManager: prepareNavigationBarInfo() DecorView@97a79ca[bVNC]
05-12 15:21:14.656 26566 26566 D InputMethodManager: getNavigationBarColor() -855310
05-12 15:21:14.656 26566 26566 V InputMethodManager: Starting input: tba=com.iiordanov.freebVNC ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
05-12 15:21:14.656 26566 26566 D InputMethodManager: startInputInner - Id : 2
05-12 15:21:14.656 26566 26566 I InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
05-12 15:21:14.659 26566 26566 D InputTransport: Input channel destroyed: 'ClientS', fd=67
05-12 15:21:14.661 26566 26586 D OpenGLRenderer: makeCurrent EglSurface : 0x0 -> 0x736c563b80
05-12 15:21:14.661 26566 26566 E ViewRootImpl: sendUserActionEvent() mView returned.
05-12 15:21:14.757 26566 26566 D ViewRootImpl: updatePointerIcon pointerType = 10121, calling pid = 26566
05-12 15:21:14.757 26566 26566 D InputManager: setPointerIconType iconId = 10121, callingPid = 26566
05-12 15:21:15.316 26566 26566 D ViewRootImpl: updatePointerIcon pointerType = 1002, calling pid = 26566
05-12 15:21:15.316 26566 26566 D InputManager: setPointerIconType iconId = 1002, callingPid = 26566
05-12 15:21:15.719 26566 26566 D ViewRootImpl@7753dda[bVNC]: ViewPostIme pointer 0
05-12 15:21:15.720 26566 26566 D ViewRootImpl: updatePointerIcon pointerType = 1002, calling pid = 26566
05-12 15:21:15.721 26566 26566 D InputManager: setPointerIconType iconId = 1002, callingPid = 26566
05-12 15:21:15.823 26566 26566 D ViewRootImpl@7753dda[bVNC]: ViewPostIme pointer 1
05-12 15:21:15.825 26566 26566 D ViewRootImpl: updatePointerIcon pointerType = 1002, calling pid = 26566
05-12 15:21:15.825 26566 26566 D InputManager: setPointerIconType iconId = 1002, callingPid = 26566
</pre>
</details>

**Comment by iiordanov** [comment]
Hey,

Thanks for the report, I released a new Beta with a supposed fix - can you confirm if it's fixed? I don't have DEX.

Thanks!
iordan

**Comment by Cerlancism** [comment]
Unfortunately, it still crashes. I have sent the crash report via Android.
Here is is also a screenshot of the stacktrace
![Screenshot_20200513-153115_Market Feedback Agent](https://user-images.githubusercontent.com/28769707/81784570-a310a500-952f-11ea-880a-793fc23bff34.jpg)

**Comment by iiordanov** [comment]
Hey, I found the issue. It was only happening on devices with "large layout", hence why the crash on DEX but not without DEX. A fix will be out shortly.
