### ISSUE TITLE
bVNC Pro v5.0.8=>v5.0.9 mouse scrollwheel stops woking in debian chroot through SSH after upgrade

### ISSUE THREAD

**Issue by ShiroiKuma0** [iiordanov/remote-desktop-clients#364]
I'm using the pro version to run a debian chroot through SSH under Android, controlling it via a bluetooth mouse and keyboard.

After upgrade from 5.0.8 to 5.0.9 the mouse scrollwheel no longer scrolls anything in X in the debian chroot. It scrolls fine when just rolling back to 5.0.8 keeping the installed app settings.

**Comment by iiordanov** [comment]
Hi, thanks for reporting! This must be due to my work to support Chromebook touchpads. Let me take a look at it and fix it right up.

**Comment by iiordanov** [comment]
I've fixed the issue with https://github.com/iiordanov/remote-desktop-clients/commit/7e2ee61aba03f5ca3e8b984a1f7bced0441aaa27 and built a new apk:

https://github.com/iiordanov/remote-desktop-clients/releases/download/v5.0.9/freebVNC-v5.0.9_8-final.apk

I've also published a new beta to Google Play, but it takes a few hours to propagate.

Please do let me know if you find other issues!

**Comment by ShiroiKuma0** [comment]
Hi, it seems you didn't update the Pro version in Play Store – it still shows 5.0.9, so can't update.

**Comment by iiordanov** [comment]
It will still show 5.0.9, it's just a new build of 5.0.9. In advanced settings at the bottom it should say v5.0.9_115098 if it's updated to the latest build.
